#!/usr/bin/perl -w
use strict;
use Data::Dumper;

my $f = shift;

my $usage="perl $0 <LocusXDNA.txt>: data generated by GT model\n"; 
my %query=(",Gentrain" => 3,"ilmnIds" => 3,"ilmnStrand" => 3,"locusIds" => 3,"locusNames" => 3,"olicodeNames" => 3,"snps" => 3,"plusMinusStrand" => 3,"locus," => 3);
my @callMatrix=("calls");
my @scoreMatrix=("Score_Call");

open(IN,$f) or die "Cann't open file '$f':\n$usage";
  my %generalInfo;
  my @call;
  my @score;
  while(my $txt = <IN>) {
    $txt =~ s/^\s+//;
    $txt =~ s/\s+$//;
    if ($txt =~ /calls/) {
      my @f = split(/,/,$txt);
      my $numf = @f;
      $numf--;
      push @call,[@f[0,8..$numf]];
    } elsif ($txt =~ /Score_Call/) {
      my @f = split(/,/,$txt);
      my $numf = @f;
      $numf--;
      push @score,[@f[0,8..$numf]];
    } else {
      foreach my $q (keys %query) {
        if ($txt =~ /$q/) {
          my @f = split(/,/,$txt); 
          my $numf = @f;
          $numf--;
          $generalInfo{$q} = [@f[$query{$q}..$numf]];
        }
      }
    }
  }
close(IN);

print STDERR "Number of general Information:", scalar(keys %generalInfo),"\n";
foreach my $k (keys %generalInfo){
  print STDERR $k,":",scalar(@{$generalInfo{$k}}),"\n";
}
print STDERR "Number of samples:",scalar(@call),"\n"; 
print STDERR "Number of locus:", scalar(@{$call[0]}),"\n";

my @generalKey = keys %generalInfo;
my $header = join(",",@generalKey);
$header =~ s/^,+//;
$header =~ s/,+/,/g;
$header =~ s/,+$//;
print $header,",";
for (my $i = 0; $i < @call; $i++) {
  print $call[$i]->[0],"_g,";
}

for (my $i = 0; $i < @score; $i++) {
  print $score[$i]->[0],"_s,";
}
print "\n";

for (my $i = 0; $i < scalar(@{$generalInfo{$generalKey[0]}}); $i++){
  foreach my $k (@generalKey) {
    print $generalInfo{$k}->[$i],",";
  }
  for (my $j = 0; $j < @call; $j ++) {
    print $call[$j]->[$i+1],",";
  } 

  for (my $j = 0; $j < @score; $j ++) {
    print $score[$j]->[$i+1],",";
  } 
  print "\n";
}
